"""
Module 05: In-Context Learning (ICL) Deep Dive vs. Associated Foundation Model Learning Paradigms

This module comprehensively covers In-Context Learning (ICL) and implements executable demonstrations
comparing it against all major associated learning and adaptation paradigms utilized across the AI industry.

-------------------------------------------------------------------------------------------------
### THE 6 PRIMARY ADAPTATION & LEARNING PARADIGMS
-------------------------------------------------------------------------------------------------
1. In-Context Learning (ICL):
   - Type: Inference-Time Transient Meta-Learning.
   - Mechanism: The model induces task patterns directly from the input sequence context window. 
     Internal parameter weight matrices remain completely frozen. Zero backpropagation occurs.

2. Few-Shot Alignment / Conditioning:
   - Type: In-Context Prompt Conditioning.
   - Mechanism: Curating 1 to 5 structural Input/Output exemplars to teach non-standard formats 
     (JSON/XML) or strict boundary conditions without weight alteration.

3. Chain-of-Thought (CoT) Test-Time Meta-Learning:
   - Type: Compute-Optimized Inference Learning.
   - Mechanism: Unlocking multi-step spatial and logical intermediate reasoning strings before concluding. 
     Allows models to backtrack or parse sub-problems dynamically.

4. Supervised Fine-Tuning (SFT):
   - Type: Static Weight Optimization.
   - Mechanism: Modifying base foundational layers using high-quality curated pairs (Instruction, Output) 
     via gradient descent to permanently alter base weight probability distributions.

5. Alignment via RLHF / DPO:
   - Type: Preference Reward Optimization.
   - Mechanism: Training a reward model on human comparisons to steer base model generations away 
     from toxic, unhelpful, or evasive completion vectors.

6. Model Distillation:
   - Type: Teacher-Student Compression.
   - Mechanism: Using synthetic Chain-of-Thought datasets generated by massive frontier models 
     (e.g., GPT-4o) to train hyper-efficient compact architectures (e.g., Llama-3-8B).

-------------------------------------------------------------------------------------------------
### EXECUTABLE DEMONSTRATIONS
-------------------------------------------------------------------------------------------------
Below, we demonstrate simulating both transient In-Context learning paths and fine-tuned structured alignment.
"""

import os
import json
import logging
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate, FewShotChatMessagePromptTemplate

# Professional logging setup
logging.basicConfig(level=logging.INFO, format='\n%(message)s')
logger = logging.getLogger(__name__)

load_dotenv()

def get_model():
    api_key = os.getenv("GOOGLE_API_KEY", "")
    if not api_key or api_key == "your_gemini_api_key_here":
        return None
    try:
        return ChatGoogleGenerativeAI(model="gemini-1.5-flash", temperature=0.0)
    except:
        return None

def demonstrate_in_context_learning_transience(llm):
    """
    Demonstrates pure In-Context Learning. The model adapts to execute a completely custom,
    non-standard logic schema dynamically inside the active session window.
    """
    logger.info("="*75)
    logger.info("1. EXECUTING IN-CONTEXT LEARNING (TRANSIENT ADAPTATION)")
    logger.info("="*75)

    # We teach a custom string notation: string reversal prefixed by an authorization checksum
    examples = [
        {"input": "Encrypt payload: Alpha", "output": "[SEC-AUTH: TRUE] | ahlpA"},
        {"input": "Encrypt payload: Delta", "output": "[SEC-AUTH: TRUE] | atleD"}
    ]

    example_prompt = ChatPromptTemplate.from_messages([
        ("human", "{input}"),
        ("ai", "{output}")
    ])

    few_shot_template = FewShotChatMessagePromptTemplate(
        example_prompt=example_prompt,
        examples=examples
    )

    final_prompt = ChatPromptTemplate.from_messages([
        ("system", "Induce the string transformation logic and structural schema shown in the examples."),
        few_shot_template,
        ("human", "{user_input}")
    ])

    test_payload = "Encrypt payload: SecureData"
    
    logger.info("[In-Context Demonstration Exemplars Injected]:")
    for ex in examples:
        logger.info(f"  Input:  {ex['input']}")
        logger.info(f"  Output: {ex['output']}\n")

    logger.info(f"[Live Session Input]: {test_payload}")

    if llm:
        try:
            res = (final_prompt | llm).invoke({"user_input": test_payload})
            logger.info(f"[ICL Output]: {res.content.strip()}")
            return
        except Exception as e:
            logger.error(f"[API Error]: {str(e)}")

    # Executable Simulation output matching true LCEL execution exactly
    logger.info("[Simulated ICL Output]: [SEC-AUTH: TRUE] | ataDeruceS")
    logger.info("\n[Architectural Takeaway]: The attention heads dynamically map the character inversion and header patterns directly at query time. No static weight adjustments occurred.")


def contrast_with_fine_tuning_schema():
    """
    Demonstrates preparing the identical logical schema for Supervised Fine-Tuning (SFT).
    Fine-tuning permanently bakes this schema alignment into weights.
    """
    logger.info("\n" + "="*75)
    logger.info("2. CONTRAST: PREPARING IDENTICAL LOGIC FOR SUPERVISED FINE-TUNING (SFT)")
    logger.info("="*75)

    sft_training_record = {
        "messages": [
            {"role": "system", "content": "You are a custom string encryption node."},
            {"role": "user", "content": "Encrypt payload: SecureData"},
            {"role": "assistant", "content": "[SEC-AUTH: TRUE] | ataDeruceS"}
        ]
    }

    logger.info("[SFT JSONL Record Payload]:")
    logger.info(json.dumps(sft_training_record, indent=2))
    logger.info("\n[Architectural Takeaway]: SFT optimizes internal parameter weights over thousands of these JSONL structures via backpropagation to permanently internalize the output layout.")


if __name__ == "__main__":
    llm = get_model()
    demonstrate_in_context_learning_transience(llm)
    contrast_with_fine_tuning_schema()
